apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: dd_agent_cluster
    registry: docker.io/datadog
    site: datadoghq.eu
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key

  features:
    apm:
      enabled: true

  template:
    spec:
      volumes:
        - name: datadog-agent-postgres-config
          configMap:
            name: datadog-agent-postgres-config
      containers:
        - name: datadog-agent
          volumeMounts:
            - name: datadog-agent-postgres-config
              mountPath: /etc/datadog-agent/conf.d/postgres.d
              readOnly: true
