apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-calculator
  template:
    metadata:
      labels:
        app: nodejs-calculator
    spec:
      containers:
      - name: nodejs-calculator
        image: hirdeshkumar2407/nodejs-calculator:1.0
        ports:
        - containerPort: 3000
